language: scala
sudo: false

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

jobs:
  include:
    - stage: Test
      script: sbt +test
