language: scala
dist: bionic

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

jobs:
  include:
    - stage: Test
      script: sbt +test
    # coverage only runs on 2.12 openjdk11
    - jdk: openjdk11
      stage: Coverage
      script: sbt ++2.12.10 coverage test coverageReport coverageAggregate && bash <(curl -s https://codecov.io/bash)
