name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: corretto
      - name: Run tests
        run: sbt +test mimaReportBinaryIssues headerCheckAll "scalafixAll --check" scalafmtCheckAll